// react/src/operations/Remove.jsx
import React, { useEffect, createRef } from "react";
import ReactDOM from "react-dom"

class Remove extends React.Component {

    constructor(props){
        super(props);
        this.state = {
            title : "title",
            show: true
        }
    }
    
    componentDidUpdate(){   
        console.timeEnd("test");
    }

    handleClick(){
        this.setState({
            show : false
        })
        console.time("test")
    }

    render(){
        if(this.state.show){
            return (
                <div>
                    <button onClick={this.handleClick.bind(this)}>Remove elements</button>
                    {
                        [...Array(1000)].map((e,i) => {
                            return (
                                <div key={i}>
                                    <div>{i}</div>
                                </div>
                            )
                        })
                    }
                </div>	
            )
        }else{
            return null;
        }
    }    

}

export default Remove

// svelte/src/operations/Remove.svelte
<script>
import { afterUpdate } from "svelte";

    let show = true;

    function handleClick(event) {
        show = false;
        console.time("test")
    }
    
    afterUpdate(() => {
        console.timeEnd("test")
    })

</script>

    {#if show}
	<div>
        <button on:click={handleClick}>Remove elements</button>
        {#each [...Array(1000)] as _, i}
            <div>
                <p>{i}</p>
            </div>
        {/each}
    </div>
    {:else}
        <div></div>
    {/if}
