// svelte/src/operations/Insert.svelte
<script>
    import { afterUpdate, onMount } from 'svelte';

    let show = false;

    afterUpdate(() => {
        console.timeEnd("test")
    })

    function handleClick(){
        show = true
        console.time("test")
    }
</script>

{#if show}
	<div>
        {#each [...Array(1000)] as _, i}
            <div>
                <p>{i}</p>
            </div>
        {/each}
    </div>
{:else}
    <div>
        <button on:click={handleClick}>Insert elements</button>
    </div>
{/if}

// react/src/operations/Insert.jsx
import React from "react";

class Insert extends React.Component {

    constructor(props){
        super(props);
        this.state = {
            show: false
        }
    }

    componentDidUpdate(){
        //elements are inserted into the dom
        console.timeEnd("test")
    }

    handleClick(){
        this.setState({
            show : true
        })
        console.time("test")
    }


    render(){
        //elements start to get rendered
        if(this.state.show){
            return (
                <>
                    {
                        [...Array(1000)].map((e,i) => {
                            return (
                                <div key={i}>
                                    <p>{i}</p>
                                </div>
                            )
                        })
                    }
                </>
            )
        }else{
            return (
                <div>
                    <button onClick={this.handleClick.bind(this)}>Click me</button>
                </div>
            )
        }
    }    

}

export default Insert
