// svelte/src/operations/Update.svelte
<script>
    import { afterUpdate, beforeUpdate } from 'svelte';

    let title = "title"

    //component is updated in the dom
    afterUpdate(() => {
        console.timeEnd("test")
    });

    function handleClick(event) {
        title = Math.random().toString(36).substr(2, 5)
        console.time("test")
	}

</script>

<div>
    <button on:click={handleClick}>Update elements</button>
	{#each [...Array(1000)] as _, i}
        <div>
            <p>{title}</p>
        </div>
	{/each}
</div>

// react/src/operations/Update.jsx
import React from "react";

class Update extends React.Component {

    constructor(props){
        super(props);
        this.state = {
            title : "title"
        }
    }

    //component is updated in the dom
    componentDidUpdate(){   
        console.timeEnd("test");
    }

    handleClick(){
        this.setState({
            title : Math.random().toString(36).substr(2, 5)
        })
        console.time("test");
    }

    render(){
        return (
            <div>
                <button onClick={this.handleClick.bind(this)}>Update elements</button>
                {
                    [...Array(1000)].map((e,i) => {
                        return (
                            <div key={i}>
                                <p>{this.state.title}</p>
                            </div>
                        )
                    })
                }
            </div>
        )
    }    

}

export default Update
